vich_uploader:
    db_driver: orm

    mappings: # You can define as many mappings as you want
        featured_images:
            uri_prefix: '%app.path.featured_images%' # Path to featured images
            namer: Vich\UploaderBundle\Naming\UniqidNamer # Unique file name
            upload_destination: '%kernel.project_dir%/public%app.path.featured_images%' # Path to featured images
