vich_uploader:
    db_driver: orm
    twig: true
    metadata:
        type: attribute

    mappings: # You can define as many mappings as you want
        featured_images:
            uri_prefix: /uploads/images # Path to featured images ' '%app.path.featured_images%'
            upload_destination:  '%kernel.project_dir%/public/uploads/images' # Path to featured images
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # Unique file name
